### ISSUE TITLE
Incorrect NPC interaction with barnacles.

### ISSUE THREAD

**Issue by malortie** [Jordon87/source-sdk-2013#13]
I created a test map with a barnacle above each of the following entities:

```
npc_chris
npc_citizen
npc_citizen_old
npc_john
npc_mike
```

In the original mod, the following entities are killed:

```
npc_chris
npc_citizen
npc_citizen_old
npc_mike
```

In the current build, as of aada0194c370ba90b35cf85ebf3d544cfc772cf1 the following entities are killed:

```
npc_citizen
npc_citizen_old
npc_john
```

All of the aforementioned entities should be killed except John.

[test_barnacle.zip](https://github.com/Jordon87/source-sdk-2013/files/15286393/test_barnacle.zip)

**Comment by Jordon87** [comment]
will try and tackle on this tomorrow.

**Comment by Jordon87** [comment]
Chris and Mike now get killed by barnacles, I didn't add Classify functions to both of them apparently,

Just for John it seems to be a special case and I need to look into it.

**Comment by Jordon87** [comment]
Seems to be pretty accurate now.

added "npc_john" to one of the exclusions for the Barnacle in it's function "CanPickup" and it now works well.
