### ISSUE TITLE
No end game message is displayed when John is killed.

### ISSUE THREAD

**Issue by malortie** [Jordon87/source-sdk-2013#32]
In the original mod, an end game message is displayed when John is killed. This happens on all skill levels.

In console:

```text
map 1187d4
ent_fire npc_john sethealth 0
```

As of c989403b2e8ddad22f96e691d8d7b082b76d3337 this does not happen.

**Comment by Jordon87** [comment]
What's interesting is that the CAI_PlayerAlly::DisplayDeathMessage function still gets called even when John dies, but the game would continue nonetheless even when he's dead.
